### ISSUE TITLE
bug: tabs persist when I switch a different graph

### ISSUE THREAD

**Issue by lef-est** [pengx17/logseq-plugin-tabs#54]
When I switch to a different graph, tabs from the previous graph are carried over. I am afraid to close those tabs because I don't want to lose that "session" when I go back to the previous graph, but 
1) obviously they take up space; 
2) if I accidentally click on a tab, a new page will be created because the current graph doesn't have those pages.

Is it possible for this plugin to keep a separate "session" for each graph?

**Comment by pengx17** [comment]
The tabs are subject to the active graph already. If it is showing tabs for other graph, this should be a bug. I happened to encounter this issue today as well and I think I have fixed it.

**Comment by lef-est** [comment]
> The tabs are subject to the active graph already. If it is showing tabs for other graph, this should be a bug. I happened to encounter this issue today as well and I think I have fixed it.

I still encounter this bug from time to time. I wonder if you can reproduce it the way I set it up:
1. Graph A has Journal enabled and set as the Home Page.
2. Graph B has Journal **disabled** . The Home Page is a custom page called [[Planner]].
3. I almost always have a few **pinned** tabs when working in Graph A.
4. When switching to Graph B, the pinned tabs in Graph A always carry over even though they do not exist in Graph B. This can be reproduced 100% on my end. (I don't mind this because I assume you and other people might have a different understanding of how the "pinned" function should work.) The bigger problem is sometimes non-pinned tabs also get carried over, which I can't always reproduce but still happens.

**Comment by pengx17** [comment]
@lef-est if you open the dev tools and see console, could you find if there are any errors reported?

**Comment by lef-est** [comment]
> @lef-est if you open the dev tools and see console, could you find if there are any errors reported?

I'm waiting for it to reappear so I can check for errors 😂 so far so good

**Comment by lef-est** [comment]
> @lef-est if you open the dev tools and see console, could you find if there are any errors reported?

Finally it happened today. Same setup described above. 
I switched to Graph B immediately after launching logseq to the default Graph A today.
![image](https://user-images.githubusercontent.com/9643637/204088969-9a98ae29-18f2-4294-a3ab-5d699eae7d30.png)
